# Generated by Django 5.0.1 on 2024-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productHeaderText', models.CharField(max_length=1000)),
                ('productPrice', models.CharField(max_length=1000)),
                ('productLink', models.CharField(max_length=1000)),
                ('productImage', models.CharField(max_length=1000)),
            ],
        ),
    ]
