# Generated by Django 5.0.1 on 2024-05-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isProductSaved',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productHeaderText',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
