# Generated by Django 5.0.1 on 2024-05-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
