# Generated by Django 5.0.1 on 2024-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_frequentlyaskedquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userMaxHeapData',
            field=models.JSONField(default=list),
        ),
    ]
