# Generated by Django 5.0.1 on 2024-05-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_user_usermaxheapdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userMaxHeapData',
        ),
    ]
