# Generated by Django 5.0.1 on 2024-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_user_usermaxheapdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxHeapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heap_data', models.TextField()),
            ],
        ),
    ]
