# Generated by Django 5.0.1 on 2024-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_delete_maxheapmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
