# Generated by Django 5.0.1 on 2024-05-26 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
